// Generated by CoffeeScript 1.6.2
(function() {
  var post;

  post = function(url, data, success) {
    return $.ajax({
      type: 'POST',
      contentType: 'application/json',
      dataType: 'json',
      "url": url,
      "data": JSON.stringify(data),
      "success": success
    });
  };

  $(function() {
    $.getJSON('customer', {}, (function(data) {
      return $('select[name=customer]').html(data.map(function(i) {
        return "<option value='" + i.id + "'>" + i.name + " " + i.surname + "</option>";
      }).join(''));
    }));
    $('input.btn[name=create]').on('click', function() {
      var data, form;

      form = document.getElementById('formCreateCustomer');
      data = {
        name: form['name'].value,
        surname: form['surname'].value,
        numberOfKMH: form['numberOfKMH'].value,
        hasOpenCredit: form['hasOpenCredit'].checked,
        finansMass: form['finansMaas'].checked,
        lastSalaryPayment: form['lastSalaryPayment'].value
      };
      return post('customer', data, (function(customer) {
        console.log('success');
        return $("<option value='" + customer.id + "'>" + customer.name + " " + customer.surname + "</option>").appendTo('select[name=customer]');
      }));
    });
    $('input.btn[name=startcampaign]').on('click', function() {
      var customer;

      customer = $('select[name=customer]').val();
      return post("campaign/start/process/" + customer, {}, (function(data) {
        return console.log('success', data);
      }));
    });
    $('input.btn[name=usecredit]').on('click', function() {
      var customer, form;

      form = document.getElementById('formAction');
      customer = $('select[name=customer]').val();
      return post("campaign/useCredit/" + customer, {}, (function() {
        return console.log('success');
      }));
    });
    $('input.btn[name=closekmh]').on('click', function() {
      var customer, enforce, form, kmh;

      form = document.getElementById('formAction');
      customer = $('select[name=customer]').val();
      enforce = form['enforce'].checked;
      kmh = Math.round(Math.random() * 100);
      return post("campaign/closekmh/" + customer + "/" + enforce + "/" + kmh, {}, (function() {
        return console.log('success');
      }));
    });
    return $('input.btn[name=ofodo]').on('click', function() {
      var customer, form, ofo;

      form = document.getElementById('formAction');
      customer = $('select[name=customer]').val();
      ofo = form['ofo'].value;
      return post("campaign/ofo/" + customer + "/" + ofo, {}, (function() {
        return console.log('success');
      }));
    });
  });

}).call(this);
